# Generated by Django 3.1.7 on 2021-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story',
            field=models.TextField(default='type here'),
        ),
    ]
