# Generated by Django 3.1.7 on 2021-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20210701_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default=None),
        ),
    ]
